---
###############
# Ant-Contrib #
###############

# ANT_HOME/lib is: /usr/local/apache-ant-*/lib

- name: Set ant-contrib version
  set_fact: antContribVersion=1.0b2
  tags: ant-contrib

- name: Set ant_lib_dir variable for on {{ ansible_distribution }} {{ ansible_architecture }}
  set_fact:
    ant_lib_dir: /usr/local/apache-ant-1.10.5/lib
  when:
  tags: ant-contrib

- debug: var=ant_lib_dir
  tags: ant-contrib

- name: Check if ant-contrib is already installed
  stat:
    path: "{{ ant_lib_dir }}/ant-contrib.jar"
  register: antcontrib_status
  tags: ant-contrib

- name: Download ant-contrib
  get_url:
    url: https://sourceforge.net/projects/ant-contrib/files/ant-contrib/ant-contrib-{{ antContribVersion }}/ant-contrib-{{ antContribVersion }}-bin.tar.gz
    dest: /tmp/
    mode: 0440
    timeout: 25
    validate_certs: no
    checksum: sha256:c9b8b1ca18b13e293688cafbd8990c940ca49104dbeefc242e5c3f8de271abdf
  retries: 3
  delay: 5
  register: antContrib_download
  until: antContrib_download is not failed
  when:
    - not antcontrib_status.stat.exists
    - ansible_distribution != "MacOSX"
    - ansible_distribution != "Solaris"
  tags: ant-contrib

- name: Download ant-contrib (macOS) and (Solaris)
  command: wget https://sourceforge.net/projects/ant-contrib/files/ant-contrib/ant-contrib-{{ antContribVersion }}/ant-contrib-{{ antContribVersion }}-bin.tar.gz -O /tmp/ant-contrib-{{ antContribVersion }}-bin.tar.gz
  retries: 3
  delay: 5
  register: antContrib_download
  until: antContrib_download is not failed
  when:
    - not antcontrib_status.stat.exists
    - ansible_distribution == "MacOSX" or ansible_distribution == "Solaris"
  tags: ant-contrib

- name: Extract ant-contrib
  unarchive:
    src: /tmp/ant-contrib-{{ antContribVersion }}-bin.tar.gz
    dest: /tmp/
    copy: False
  when: not antcontrib_status.stat.exists
  tags: ant-contrib

- name: Move ant-contrib.jar to ant lib folder
  command: mv /tmp/ant-contrib/lib/ant-contrib.jar {{ ant_lib_dir }}
  when: not antcontrib_status.stat.exists
  tags: ant-contrib

- name: Remove downloaded packages for ant-contrib
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/ant-contrib
    - /tmp/ant-contrib-{{ antContribVersion }}-bin.tar.gz
  ignore_errors: yes
  tags: ant-contrib
