---
###############
# Ant-Contrib #
###############

# ANT_HOME/lib is: /usr/local/apache-ant-*/lib

- name: Set ant_lib_dir variable for on {{ ansible_distribution }} {{ ansible_architecture }}
  set_fact:
    ant_lib_dir: /usr/local/apache-ant-1.10.5/lib
  when:
  tags: ant-contrib

- debug: var=ant_lib_dir
  tags: ant-contrib

- name: Check if ant-contrib is already installed
  stat:
    path: "{{ ant_lib_dir }}/ant-contrib.jar"
  register: antcontrib_status
  tags: ant-contrib

- name: Download ant-contrib
  get_url:
    url: https://sourceforge.net/projects/ant-contrib/files/ant-contrib/ant-contrib-1.0b2/ant-contrib-1.0b2-bin.tar.gz
    dest: /tmp/
    mode: 0440
    timeout: 25
    validate_certs: no
  when: antcontrib_status.stat.exists == False
  tags: ant-contrib

- name: Extract ant-contrib
  unarchive:
    src: /tmp/ant-contrib-1.0b2-bin.tar.gz
    dest: /tmp/
    copy: False
  when: antcontrib_status.stat.exists == False
  tags: ant-contrib

- name: Move ant-contrib.jar to ant lib folder
  command: mv /tmp/ant-contrib/lib/ant-contrib.jar {{ ant_lib_dir }}
  when:
    - antcontrib_status.stat.exists == False
  tags: ant-contrib

- name: Download junit - SLES
  get_url:
    url: https://ftp5.gwdg.de/pub/opensuse/discontinued/distribution/11.4/repo/oss/suse/noarch/junit-3.8.2-8.1.noarch.rpm
    dest: /tmp/
    mode: 0440
    timeout: 25
    validate_certs: no
  when:
    - ansible_distribution == "SLES"
  tags: ant-contrib

- name: Install junit from rpm - SLES
  yum:
    name: /tmp/junit-3.8.2-8.1.noarch.rpm
    state: present
  when:
    - ansible_distribution == "SLES"
  tags: ant-contrib
