---
###############
# Ant-Contrib #
###############

# ANT_HOME/lib is: /usr/local/apache-ant-*/lib

- name: Set ant_lib_dir variable for on {{ ansible_distribution }} {{ ansible_architecture }}
  set_fact:
    ant_lib_dir: /usr/local/apache-ant-1.10.5/lib
  when:
  tags: ant-contrib

- debug: var=ant_lib_dir
  tags: ant-contrib

- name: Check if ant-contrib is already installed
  stat:
    path: "{{ ant_lib_dir }}/ant-contrib.jar"
  register: antcontrib_status
  tags: ant-contrib

- name: Download ant-contrib
  get_url:
    url: https://sourceforge.net/projects/ant-contrib/files/ant-contrib/ant-contrib-1.0b2/ant-contrib-1.0b2-bin.tar.gz
    dest: /tmp/
    mode: 0440
    timeout: 25
    validate_certs: no
    checksum: sha256:c9b8b1ca18b13e293688cafbd8990c940ca49104dbeefc242e5c3f8de271abdf
  retries: 3
  delay: 5
  register: antContrib_download
  until: antContrib_download is not failed
  when: antcontrib_status.stat.exists == False
  tags: ant-contrib

- name: Extract ant-contrib
  unarchive:
    src: /tmp/ant-contrib-1.0b2-bin.tar.gz
    dest: /tmp/
    copy: False
  when: antcontrib_status.stat.exists == False
  tags: ant-contrib

- name: Move ant-contrib.jar to ant lib folder
  command: mv /tmp/ant-contrib/lib/ant-contrib.jar {{ ant_lib_dir }}
  when:
    - antcontrib_status.stat.exists == False
  tags: ant-contrib
