---
####################################################
# ansible install adoptopenjdk8 into /usr/lib/jvm/ #
####################################################

# Conditions:
# Check if target is installed
# Proceed with installing to /usr/lib/jvm

- name: Checking for /usr/lib/jvm
  stat: path=/usr/lib/jvm
  register: usr_lib_jvm_exists
  tags: adoptopenjdk8

- name: Creating /usr/lib/jvm if not found
  file:
    path: /usr/lib/jvm
    state: directory
    owner: root
    mode: 0755
  when: usr_lib_jvm_exists.stat.exists != True
  tags: adoptopenjdk8

- name: Check if jdk8 is already installed in the target location
  shell: ls -ld /usr/lib/jvm/jdk8* >/dev/null 2>&1
  ignore_errors: yes
  register: adoptopenjdk8_installed
  tags:
    - adoptopenjdk8
    - skip_ansible_lint

- name: Install latest release if one not already installed (Linux/x64)
  unarchive:
    src: https://api.adoptopenjdk.net/v3/binary/latest/8/ga/linux/x64/jdk/{{ bootjdk }}/normal/adoptopenjdk?project=jdk
    dest: /usr/lib/jvm
    remote_src: yes
  retries: 3
  delay: 5
  register: adoptopenjdk8_download
  until: adoptopenjdk8_download is not failed
  when:
    - adoptopenjdk8_installed.rc != 0
    - ansible_architecture == "x86_64"
  tags: adoptopenjdk8

- name: Install latest release if one not already installed (Linux/s390x)
  unarchive:
    src: https://api.adoptopenjdk.net/v3/binary/latest/8/ga/linux/s390x/jdk/{{ bootjdk }}/normal/adoptopenjdk?project=jdk
    dest: /usr/lib/jvm
    remote_src: yes
  retries: 3
  delay: 5
  register: adoptopenjdk8_download
  until: adoptopenjdk8_download is not failed
  when:
    - adoptopenjdk8_installed.rc != 0
    - ansible_architecture == "s390x"
  tags: adoptopenjdk8

- name: Install latest release if one not already installed (Linux/ppc64le)
  unarchive:
    src: https://api.adoptopenjdk.net/v3/binary/latest/8/ga/linux/ppc64le/jdk/{{ bootjdk }}/normal/adoptopenjdk?project=jdk
    dest: /usr/lib/jvm
    remote_src: yes
  retries: 3
  delay: 5
  register: adoptopenjdk8_download
  until: adoptopenjdk8_download is not failed
  when:
    - adoptopenjdk8_installed.rc != 0
    - ansible_architecture == "ppc64le"
  tags: adoptopenjdk8

- name: Install latest Hotspot release if one not already installed (Linux/aarch64)
  unarchive:
    src: https://api.adoptopenjdk.net/v3/binary/latest/8/ga/linux/aarch64/jdk/{{ bootjdk }}/normal/adoptopenjdk?project=jdk
    dest: /usr/lib/jvm
    remote_src: yes
  retries: 3
  delay: 5
  register: adoptopenjdk8_download
  until: adoptopenjdk8_download is not failed
  when:
    - adoptopenjdk8_installed.rc != 0
    - ansible_architecture == "aarch64"
  tags: adoptopenjdk8

- name: Get /usr/lib/jvm/jdk8* full path name
  shell: ls -ld /usr/lib/jvm/jdk8* 2>/dev/null | awk '{print $9}'
  register: adoptopenjdk8_dir
  when:
    - adoptopenjdk8_installed.rc != 0
  tags: adoptopenjdk8

- name: Chown jdk8* directory
  file:
    path: '{{ adoptopenjdk8_dir.stdout }}'
    state: directory
    owner: root
    recurse: yes
  when: adoptopenjdk8_installed.rc != 0
  tags: adoptopenjdk8
