---
############################################################################
# cmake  - required by OpenJ9 and OpenJFX builds - requires C++11 compiler #
############################################################################

- name: Set ansible_processor_vcpus
  set_fact:
    ansible_processor_vcpus: "{{ ansible_processor_cores }}"
  when:
    - ansible_architecture == "s390x"
  tags: cmake

- name: Test if cmake is installed on path
  shell: cmake >/dev/null 2>&1
  ignore_errors: yes
  register: cmake_installed
  tags:
    - cmake
    - skip_ansible_lint

- name: Test if cmake is installed at the correct version
  shell: cmake --version 2>/dev/null | grep version | awk '{print $3}'
  when: cmake_installed.rc == 0
  register: cmake_version
  tags: cmake

- name: Download cmake
  get_url:
    url: https://cmake.org/files/v3.11/cmake-3.11.4.tar.gz
    dest: /tmp/cmake-3.11.4.tar.gz
    mode: 0440
    force: no
    validate_certs: no
    checksum: sha256:8f864e9f78917de3e1483e256270daabc4a321741592c5b36af028e72bff87f5
  when:
    - (cmake_installed.rc != 0 ) or (cmake_installed.rc == 0 and cmake_version.stdout is version_compare('3.11.4', operator='lt') )
    - (ansible_architecture == "x86_64") or (ansible_architecture == "ppc64le") or (ansible_architecture == "s390x")
  tags: cmake

- name: Extract cmake
  unarchive:
    src: /tmp/cmake-3.11.4.tar.gz
    dest: /tmp
    copy: False
  when:
    - (cmake_installed.rc != 0 ) or (cmake_installed.rc == 0 and cmake_version.stdout is version_compare('3.11.4', operator='lt') )
    - (ansible_architecture == "x86_64") or (ansible_architecture == "ppc64le") or (ansible_architecture == "s390x")
  tags: cmake

# NOTE: PATH setting is for RHEL6/CentOS6 since gcc 4.4.7 is not C++11 compliant
- name: Running ./configure & make for cmake
  shell: cd /tmp/cmake-3.11.4 && ./configure && PATH=/opt/gcc-4.8.5/bin:$PATH make -j {{ ansible_processor_vcpus }} && make install
  when:
    - (cmake_installed.rc != 0 ) or (cmake_installed.rc == 0 and cmake_version.stdout is version_compare('3.11.4', operator='lt') )
    - (ansible_architecture == "x86_64") or (ansible_architecture == "ppc64le") or (ansible_architecture == "s390x")
  tags: cmake

# cmake on armv7l
- name: Install cmake on armv7l
  apt: pkg=cmake state=latest update_cache=yes
  when:
    - ansible_architecture == "armv7l"
  tags:
    - cmake
    # TODO: Package installs should not use latest
    - skip_ansible_lint
