---
#############
# Swap_File #
#############

# Conditions:
# Test if there a swapfile already exists: /swapfile (swap_root) or /tmp/swapfile (swap_tmp)
# Already installed/exists: When swap_root.rc or swap_tmp.rc equals 0
# Not installed: When swap_root.rc or swap_tmp.rc does NOT equal 0
# Assume swap path of /swapfile override where applicable

- name: Test swapfile path - /swapfile
  command: ls /swapfile
  ignore_errors: yes
  register: swap_root
  tags:
    - swap_file
    # TODO: use stat to check file existence
    - skip_ansible_lint

- name: Test swapfile path - /tmp/swapfile
  command: ls /tmp/swapfile
  ignore_errors: yes
  register: swap_tmp
  tags:
    - swap_file
    # TODO: use stat to check file existence
    - skip_ansible_lint

- name: Set Swapfile path - /swapfile
  set_fact:
    swap_path: /swapfile
  tags: swap_file

- name: Set Swapfile path - /tmp/swapfile
  set_fact:
    swap_path: /tmp/swapfile
  when:
    - (ansible_distribution_major_version == "9" and ansible_architecture == "armv7l")
  tags: swap_file

- name: Display swapfile Debug Information
  debug:
    msg:
      - "swap_path: {{ swap_path | default('***Undefined***') }} "
      - "swap_tmp: {{ swap_tmp.rc | default('***Undefined***') }} "
      - "swap_root: {{ swap_root.rc | default('***Undefined***') }} "
  tags: swap_file

- name: Disable dphys-swapfile where applicable
  command: "dphys-swapfile uninstall"
  ignore_errors: yes
  when:
    - ansible_architecture == "armv7l"
  tags: swap_file

- name: Create swap file - via DD
  command: "dd if=/dev/zero of=/{{ swap_path }} bs=250M count=8"
  when:
    - (swap_root.rc != 0 and swap_tmp.rc != 0)
  tags: swap_file

- name: Set swap file permissions
  file: path="{{ swap_path }}"
        owner=root
        group="{{ root_group }}"
        mode=0600
  when:
    - (swap_root.rc != 0 and swap_tmp.rc != 0)
  tags: swap_file

- name: Create swap area device
  command: "mkswap {{ swap_path }}"
  when:
    - (swap_root.rc != 0 and swap_tmp.rc != 0)
  tags: swap_file

- name: Mount swap file
  command: "swapon {{ swap_path }}"
  when:
    - (swap_root.rc != 0 and swap_tmp.rc != 0)
  tags: swap_file

- name: Add swap to fstab
  mount: src="{{ swap_path }}"
    name=none
    fstype=swap
    opts=sw
    passno=0
    dump=0
    state=present
  when:
    - (swap_root.rc != 0 and swap_tmp.rc != 0)
  tags: swap_file
