---
###################################
# AdoptOpenJDK - Ansible Playbook #
###################################
- hosts: "{{ groups['Vendor_groups'] | default('localhost:build:test:!*zos*:!*win*:!*macos*:!*aix*') }}"
  gather_facts: yes
  tasks:
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

  #########
  # Roles #
  #########
  roles:
    - Debug
    - Version
    - Common
    - autoconf
    - curl
    - Jenkins_User                # AdoptOpenJDK Infrastructure
    - freemarker                  # OpenJ9
    - ant                         # Testing
    - Ant-Contrib                 # Testing
    - GIT_Source
    - CPAN
    - cmake                       # OpenJ9 / OpenJFX
    - gmake
    - Docker                      # Testing
    - NVidia_Cuda_Toolkit         # OpenJ9
    - Superuser                   # AdoptOpenJDK Infrastructure
    - Swap_File
    - Crontab
    - NTP_TIME
    - gcc_48
    - gcc_7                       # OpenJ9
    - ccache # ccache needs to be compiled/installed after compilers
    - {role: nasm, when: ansible_architecture == 'x86_64'} # OpenJ9
    - adoptopenjdk9               # JDK10 build bootstrap
    - adoptopenjdk10              # JDK11 build bootstrap
    - adoptopenjdk11              # JDK12 build bootstrap
    - OpenSSL102                  # OpenJ9
    - OpenSSL                     # OpenJ9 JITaaS
    - Protobuf                    # OpenJ9
    - Nagios_Plugins              # AdoptOpenJDK Infrastructure
    - Nagios_Master_Config        # AdoptOpenJDK Infrastructure
    - Nagios_Tunnel               # AdoptOpenJDK Infrastructure
    - Clean_Up
    - Security
    - Vendor
