---
###################################
# AdoptOpenJDK - Ansible Playbook #
###################################
# Groups can be passed in as a command-line variable in Ansible playbook.
# It can be defined as 'all' or a specific group which the host belongs to.
# For example, it can be 'all' or 'x86' for when a host is in the group 'x86'.
- hosts: "{{ Groups | default('localhost:build:test:!*zos*:!*win*:!*aix*') }}"
  gather_facts: yes
  tasks:
    - block:
      # Set standard variables
        - name: Load AdoptOpenJDKs variable file
          include_vars: group_vars/all/adoptopenjdk_variables.yml
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

  #########
  # Roles #
  #########
  roles:
    - Debug
    - Version
    - Common
    - autoconf
    - curl
    - Jenkins_User                # AdoptOpenJDK Infrastructure
    - role: freemarker            # OpenJ9
      tags: [build_tools, build_tools_openj9]
    - ant                         # Testing
    - Ant-Contrib                 # Testing
    - GIT_Source
    - gmake
    - Docker                      # Testing
    - role: NVidia_Cuda_Toolkit   # OpenJ9
      tags: [build_tools, build_tools_openj9]
    - Superuser                   # AdoptOpenJDK Infrastructure
    - Swap_File
    - Crontab
    - NTP_TIME
    - gcc_48
    - role: gcc_7                 # OpenJ9
      tags: [build_tools, build_tools_openj9]
    - role: cmake                 # OpenJ9 / OpenJFX
      tags: [build_tools, build_tools_openj9, build_tools_openjfx]
    - role: Protobuf              # OpenJ9 (JITserver)
      tags: [build_tools, build_tools_openj9]
    - ccache
    - role: nasm                  # OpenJ9
      when: ansible_architecture == 'x86_64'
      tags: [build_tools, build_tools_openj9]
    - role: adoptopenjdk_install
      jdk_version: 8
      tags: build_tools
    - role: adoptopenjdk_install  # JDK11 Build Bootstrap
      jdk_version: 10
      tags: build_tools
    - role: adoptopenjdk_install  # JDK13 Build Bootstrap
      jdk_version: 12
      tags: build_tools
    - role: adoptopenjdk_install  # JDK14 Build Bootstrap
      jdk_version: 13
    - OpenSSL102                  # OpenJ9
    - Nagios_Plugins              # AdoptOpenJDK Infrastructure
    - Nagios_Master_Config        # AdoptOpenJDK Infrastructure
    - Nagios_Tunnel               # AdoptOpenJDK Infrastructure
    - Clean_Up
    - Security
    - Vendor
