---
###################################
# AdoptOpenJDK - Ansible Playbook #
###################################
# Groups can be passed in as a command-line variable in Ansible playbook.
# It can be defined as 'all' or a specific group which the host belongs to.
# For example, it can be 'all' or 'x86' for when a host is in the group 'x86'.
- name: Ansible Unix playbook
  hosts: "{{ Groups | default('localhost:build:test:perf:jck:!*zos*:!*win*:!*aix*') }}"
  gather_facts: yes
  tasks:
    - name: Run Tasks
      block:
      # Set standard variables
        - name: Load AdoptOpenJDKs variable file
          include_vars: group_vars/all/adoptopenjdk_variables.yml
  environment:
    PATH: "/opt/csw/bin/:/usr/local/bin:/opt/homebrew/bin:{{ ansible_env.PATH }}"

  #########
  # Roles #
  #########
  roles:
    - role: logs
      position: "Start"
      tags: always
    - Debug
    - role: Get_Vendor_Files
      tags: [vendor_files, adoptopenjdk, jenkins_user, nagios_plugins, superuser]
    - Version
    - role: adoptopenjdk_install  # Previous LTS
      jdk_version: 17
      when:
        - ansible_distribution != "Solaris"
      tags: build_tools
    - role: logs
      position: "End"
      tags: always
