---
#######
# X11 #
#######
- name: Create X11 Wrapper config file
  copy:
    content: |
      allowed_users=anybody
      needs_root_rights=yes
    dest: /etc/X11/Xwrapper.config
    group: "{{ root_group }}"
    owner: root
    mode: 0644
  tags: x11

- name: Start X11
  become: yes
  become_user: "{{ Jenkins_Username }}"
  shell: startx -- :1 &
  ignore_errors: yes
  no_log: True
  tags:
    - x11
    # TODO: write a condition when NOT to run this step
    - skip_ansible_lint
