---
#########################################################################################
# AdoptOpenJDK - Ansible Playbook to install Nagios plugins on CentOS 7 on x86 hardware #
#########################################################################################

###########################################################################
# License Information:                                                    #
# Nagios core and its plugins are lincesed under GPL                      #
# For more information please see: https://www.nagios.com/legal/licenses/ #
###########################################################################

###############
# Nagios user #
###############
- name: Allow Nagios to use pkg while restricting it to audit only
  shell: |
    echo "nagios ALL = NOPASSWD: /usr/sbin/pkg audit -F" >> /etc/sudoers
  tags: [nagios_plugins, adoptopenjdk]

- name: Allow Nagios to use pkg while restricting it to upgrade --dry-run only
  shell: |
    echo "nagios ALL = NOPASSWD: /usr/sbin/pkg upgrade --dry-run" >> /etc/sudoers
  tags: [nagios_plugins, adoptopenjdk]

###################
# Install plugins #
###################
- name: Download nagios-plugins
  get_url:
    url: https://nagios-plugins.org/download/nagios-plugins-2.2.1.tar.gz
    dest: /tmp/
    mode: 0440
    timeout: 25
    checksum: sha256:647c0ba4583d891c965fc29b77c4ccfeccc21f409fdf259cb8af52cb39c21e18
  tags: [nagios_plugins, adoptopenjdk]

- name: Extract nagios-plugins
  unarchive:
    src: /tmp/nagios-plugins-2.2.1.tar.gz
    dest: /tmp/
    copy: False
  tags: [nagios_plugins, adoptopenjdk]

- name: Configure, make and make install nagios-plugins
  shell: cd /tmp/nagios-plugins-2.2.1/ && ./configure --prefix=/usr/local/nagios && make -j {{ ansible_processor_vcpus }} && make install
  become: yes
  tags: [nagios_plugins, adoptopenjdk]

##############################
# Install additional plugins #
##############################
- name: Download add-on check_pkg plugin
  get_url:
    url: https://raw.githubusercontent.com/AdoptOpenJDK/openjdk-infrastructure/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/check_pkg
    dest: /usr/local/nagios/libexec/check_pkg
    mode: 0755
    checksum: sha256:1ccbd48c22dfc42f712f31d09b2509cc93f2b5ef7bb804ba1d0d7db0a4803874
  tags: [nagios_plugins, adoptopenjdk]
