---
# AdoptOpenJDK variables file
Jenkins_User_SSHKey: /Vendor_Files/keys/id_rsa.pub
Zeus_User_SSHKey: /Vendor_Files/keys/zeus.key
Nagios_User_SSHKey: /Vendor_Files/keys/nagios.key
Jenkins_Username: jenkins
Nagios_Plugins: Enabled
Slack_Notification: Disabled
Superuser_Account: Enabled
jckftp_Username: jckftp
jckftp_Passwd: /Vendor_Files/passwords/ftp
# Jcktestr User Variables:
Jcktestr_Username: jcktestr
Jcktestr_User_SSHKey: /Vendor_Files/keys/keybox.key
