---
#######
# GIT #
#######

- name: Test if GIT is already installed
  win_stat:
    path: 'C:\Program Files\Git'
  register: git_installed
  tags: git

- name: Check if GIT installer is already downloaded
  win_stat:
    path: 'C:\temp\git.exe'
  register: git_download
  tags: git

- name: Download GIT installer
  win_shell: '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; wget https://github.com/git-for-windows/git/releases/download/v2.24.1.windows.2/Git-2.24.1.2-64-bit.exe -Outfile C:/temp/git.exe'
  when: (git_download.stat.exists == false) and (git_installed.stat.exists == false)
  tags: git

- name: Install GIT
  win_command: 'C:\temp\git.exe /SILENT /COMPONENTS="icons,ext\reg\shellhere,assoc,assoc_sh"'
  when: (git_installed.stat.exists == false)
  tags: git
