---
###################
# freetype v2.5.3 #
###################

- name: Test if freetype is already installed
  win_stat:
    path: 'C:\openjdk\freetype-2.5.3'
  register: freetype_installed
  tags: Freetype

- name: Test if freetype is already downloaded
  win_stat:
    path: 'C:\temp\ft253.zip'
  register: freetype_download
  tags: Freetype

- name: Download freetype 2.5.3
  win_get_url:
    url: https://sourceforge.net/projects/freetype/files/freetype2/2.5.3/ft253.zip/download
    dest: C:\temp\ft253.zip
  when: (freetype_installed.stat.exists == false) and (freetype_download.stat.exists == false)
  tags: Freetype

- name: Unpack freetype
  win_unzip:
    src: C:\temp\ft253.zip
    dest: C:\openjdk
    delete_archive: yes
  when: (freetype_installed.stat.exists == false) and (freetype_download.stat.exists == false)
  tags: Freetype

- name: Add modify, write permissions for jenkins user
  win_acl:
    path: C:\openjdk\freetype-2.5.3
    user: "{{ Jenkins_Username }}"
    rights: Read,Write,Modify,FullControl,Delete
    type: allow
    state: present
  when: (freetype_installed.stat.exists == false)
  tags: Freetype

- name: Check if freetype 32bit has been built
  win_shell: Test-Path -Path C:\openjdk\freetype-2.5.3\lib32
  register: freetype32_built
  tags: Freetype

- name: Check if freetype 64bit has been built
  win_shell: Test-Path -Path C:\openjdk\freetype-2.5.3\lib64
  register: freetype64_built
  tags: Freetype

- name: Build freetype-2.5.3 32bit
  win_shell: |
    msbuild.exe C:/openjdk/freetype-2.5.3/builds/windows/vc2010/freetype.vcxproj /p:PlatformToolset=v100 /p:Configuration="Release Multithreaded" /p:PlatformTarget=x86 /p:ConfigurationType=DynamicLibrary /p:TargetName=freetype /p:OutDir="C:/openjdk/freetype-2.5.3/lib32/" /p:IntDir="C:/openjdk/freetype-2.5.3/obj32/" > C:/temp/freetype32.log
    msbuild.exe C:/openjdk/freetype-2.5.3/builds/windows/vc2010/freetype.vcxproj /p:PlatformToolset=v100 /p:Configuration="Release Multithreaded" /p:PlatformTarget=x86 /p:ConfigurationType=StaticLibrary /p:TargetName=freetype /p:OutDir="C:/openjdk/freetype-2.5.3/lib32/" /p:IntDir="C:/openjdk/freetype-2.5.3/obj32/" >> C:/temp/freetype32.log
  args:
    executable: C:\Windows\system32\cmd.exe /k ""C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat"" x86
  when: (freetype32_built == False)
  tags: Freetype

- name: Build freetype-2.5.3 64bit
  win_shell: |
    msbuild.exe C:/openjdk/freetype-2.5.3/builds/windows/vc2010/freetype.vcxproj /p:PlatformToolset=v100 /p:Configuration="Release Multithreaded" /p:Platform=x64 /p:ConfigurationType=DynamicLibrary /p:TargetName=freetype /p:OutDir="C:/openjdk/freetype-2.5.3/lib64/" /p:IntDir="C:/openjdk/freetype-2.5.3/obj64/" > C:/temp/freetype64.log
    msbuild.exe C:/openjdk/freetype-2.5.3/builds/windows/vc2010/freetype.vcxproj /p:PlatformToolset=v100 /p:Configuration="Release Multithreaded" /p:Platform=x64 /p:ConfigurationType=StaticLibrary /p:TargetName=freetype /p:OutDir="C:/openjdk/freetype-2.5.3/lib64/" /p:IntDir="C:/openjdk/freetype-2.5.3/obj64/" >> C:/temp/freetype64.log
  args:
    executable: C:\Windows\system32\cmd.exe /k ""C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat"" x86
  when: (freetype64_built == False)
  tags: Freetype
