---
##########
# Ubuntu #
##########

#########################################
# Configure Repos and Update the system #
#########################################
- name: Add the openjdk repository to apt
  apt_repository: repo='ppa:openjdk-r/ppa'
  when:
    - ansible_architecture != "armv7l"
  tags: patch_update

- name: Add the ubuntu toolchain repository to apt
  apt_repository: repo='ppa:ubuntu-toolchain-r/test'
  when:
    - ansible_architecture != "armv7l"
  tags: patch_update

- name: Add Azul Zulu repository for x86_64
  apt_repository: repo='deb http://repos.azulsystems.com/ubuntu stable main'
  when:
    - ansible_architecture == "x86_64"
  tags: patch_update

- name: Add Azul Zulu GPG Package Signing Key for x86_64
  apt_key:
    url: http://repos.azulsystems.com/RPM-GPG-KEY-azulsystems
    state: present
  when:
    - ansible_architecture == "x86_64"
  tags: [patch_update, azul-key]

- name: Add additional repositories for BeagleBone
  apt_repository: repo={{ item }}
  with_items:
    - deb https://deb.debian.org/debian/ stable main contrib non-free
    - deb-src https://deb.debian.org/debian/ stable main contrib non-free
    - deb https://deb.debian.org/debian/ stable-updates main contrib non-free
    - deb-src https://deb.debian.org/debian/ stable-updates main contrib non-free
    - deb https://deb.debian.org/debian-security stable/updates main
    - deb-src https://deb.debian.org/debian-security stable/updates main
    - deb http://ftp.debian.org/debian stretch-backports main
    - deb-src http://ftp.debian.org/debian stretch-backports main
  when:
    - (ansible_distribution_major_version == "9" and ansible_architecture == "armv7l")
  tags: patch_update

- name: Run apt-get upgrade
  apt: upgrade=safe update_cache=yes
  tags: patch_update

############################
# Build Packages and tools #
############################
- name: Call Build Packages and Tools Task
  include_tasks: build_packages_and_tools.yml

##########################
# Additional build tools #
##########################
- name: Call Build Packages and Tools Task for OpenJFX
  package: "name={{ item }} state=latest"
  with_items: "{{ OpenJFX_Build_Tool_Packages }}"
  tags: [build_tools, build_tools_jfx]

- name: Install GCC G++ on supported platforms
  package: "name={{ item }} state=latest"
  with_items: "{{ gcc_compiler }}"
  when:
    - (ansible_distribution_major_version != "9" and ansible_architecture != "armv7l")
  tags: build_tools

- name: Install additional build tools for x86_64
  package: "name={{ item }} state=latest"
  with_items: "{{ Additional_Build_Tools_x86_64 }}"
  when:
    - ansible_architecture == "x86_64"
  tags: build_tools

- name: Install additional build tools for PPC64LE
  package: "name={{ item }} state=latest"
  with_items: "{{ Additional_Build_Tools_ppc64le }}"
  when:
    - ansible_architecture == "ppc64le"
  tags: build_tools

- name: Install additional build tools for S390
  package: "name={{ item }} state=latest"
  with_items: "{{ Additional_Build_Tools_s390 }}"
  when:
    - ansible_architecture == "s390x"
  tags: build_tools

- name: Install additional build tools for aarch64
  package: "name={{ item }} state=latest"
  with_items: "{{ Additional_Build_Tools_aarch64 }}"
  when:
    - ansible_architecture == "aarch64"
  tags: build_tools

#########################
# Additional Test Tools #
#########################
- name: Install additional Test Tool Packages for x86_64
  package: "name={{ item }} state=latest"
  with_items: "{{ Test_Tool_Packages_x86_64 }}"
  when:
    - ansible_architecture == "x86_64"
  tags: test_tools

- name: Install xserver-xorg-legacy on Ubuntu 16
  apt: name=xserver-xorg-legacy state=installed
  when:
    - ansible_distribution_major_version == "16"
  tags: test_tools

- name: Install libfreetype6-dev on Ubuntu 16 s390x
  apt: name=libfreetype6-dev state=installed
  when:
    - ansible_architecture == "s390x"
  tags: test_tools

####################
# Set default Java #
####################
- name: Set default java version for x86_64
  shell: update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  when:
    - (ansible_distribution_major_version == "14" and ansible_architecture == "x86_64") or
      (ansible_distribution_major_version == "16" and ansible_architecture == "x86_64")
  tags: default_java

- name: Set default java version for armv7l
  shell: update-alternatives --set java /usr/lib/jvm/java-8-openjdk-armhf/jre/bin/java
  when:
    - ansible_architecture == "armv7l"
  tags: default_java

- name: Set default java version for ppc64le
  shell: update-alternatives --set java /usr/lib/jvm/java-8-openjdk-ppc64el/jre/bin/java
  when:
    - ansible_distribution_major_version == "14"
    - ansible_architecture == "ppc64le"
  tags: default_java
