---
###########
# Xcode10 #
###########
- name: Get macOS version
  shell: sw_vers -productVersion
  register: macos_version

- name: Set xcode_needed to false
  set_fact:
    xcode_needed: false

- name: Check if Xcode is needed on this machine
  set_fact:
    xcode_needed: true
  when:
    - inventory_hostname | regex_search("test-")
    # We only want to install on test-*macos.14 or test-*macos10.15
    - macos_version | regex_search("10.14") or macos_version | regex_search("10.15")

- name: Check if Xcode is installed
  stat:
    path: /Applications/Xcode.app/
  when: xcode_needed == true
  register: xcode_installed

- name: Check if Xcode is downloaded
  stat:
    path: /tmp/xcode10.xip
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: xcode_downloaded
  when:
    - xcode_needed == true
    - not xcode_installed.stat.exists

- name: Check if Xcode is extracted
  stat:
    path: Xcode.app
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: xcode_extracted
  when:
    - xcode_needed == true
    - not xcode_installed.stat.exists

# Stored in Azure Blob Storage (SAS URL set to expire in 2030)
- name: Download Xcode_10.3.xip (very slow)
  get_url:
    url: "https://ansiblestorageadopt.blob.core.windows.net/xcode10/Xcode_10.3.xip?{{ Xcode10_SAS_TOKEN }}"
    dest: /tmp/xcode10.xip
    force: no
    mode: 0755
    checksum: sha256:7a3fd9dc1b0a95d6179c44a92e3f108a928f62a122782671ef1575ed75ea6e9d
  when:
    - xcode_needed == true
    - not xcode_installed.stat.exists
    - not xcode_extracted.stat.exists
    - not xcode_downloaded.stat.exists

- name: Extract Xcode10
  command: xip -x /tmp/xcode10.xip
  when:
    - xcode_needed == true
    - not xcode_installed.stat.exists
    - not xcode_extracted.stat.exists

- name: Move Xcode10 to /Applications
  command: mv Xcode.app /Applications/
  when:
    - xcode_needed == true
    - not xcode_installed.stat.exists

- name: Set Xcode 10 as default keychain
  command: xcode-select -s /Applications/Xcode.app
  when:
    - xcode_needed == true
    - not xcode_installed.stat.exists

- name: Accept Xcode 10 License
  command: xcodebuild -license accept
  when:
    - xcode_needed == true
    - not xcode_installed.stat.exists

- name: Remove downloaded packages for Xcode10
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/xcode10.xip
  ignore_errors: yes
