---
###################################
# Visual Studio 2010 Professional #
###################################
- name: Test if VS 2010 is already installed
  win_stat:
    path: 'C:\Program Files (x86)\Microsoft Visual Studio 10.0'
  register: vs2010_installed
  tags: MSVS_2010

- name: Download Visual Studio 2010 Professional
  win_get_url:
    url: 'https://download.microsoft.com/download/D/B/C/DBC11267-9597-46FF-8377-E194A73970D6/vs_proweb.exe'
    dest: 'C:\temp\vs2010_professional.exe'
    checksum: a03ef907e301ae9fc81c6b8bbe17112a449f1ab6c79eaa623b6e50a6cec366ba
    checksum_algorithm: sha256
  when: (not vs2010_installed.stat.exists)
  tags: MSVS_2010

- name: Install Visual Studio 2010 Professional
  raw: 'C:\temp\vs2010_professional.exe /q /norestart /nocache'
  when: (not vs2010_installed.stat.exists)
  tags: MSVS_2010

- name: Register Visual Studio 2010 DIA SDK shared libraries
  win_command: 'regsvr32 /s "{{ item }}"'
  with_items:
    - c:\Program Files (x86)\Microsoft Visual Studio 10.0\DIA SDK\bin\msdia100.dll
    - c:\Program Files (x86)\Microsoft Visual Studio 10.0\DIA SDK\bin\amd64\msdia100.dll
  tags: MSVS_2010

# NOTE: This construct is because an SQL Server entry is being added to
# the path which has an erroneous quote in it, causing OpenSSL not to build
# See: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1485
- name: Remove double quote from %PATH%
  win_shell: |
    $NewPath=$env:path.Replace('"','')
    [Environment]::SetEnvironmentVariable("Path", $NewPath, [System.EnvironmentVariableTarget]::Machine)
  args:
    executable: powershell
  when: (not vs2010_installed.stat.exists)
  tags: MSVS_2010

- name: Reboot machine after Visual Studio 2010 installation
  win_reboot:
    reboot_timeout: 1800
    shutdown_timeout: 1800
  when: (not vs2010_installed.stat.exists)
  tags: MSVS_2010
