---
########################################
# AdoptOpenJDK 11 for bootstrapping 11 #
########################################
- name: Checking for /usr/lib/jvm
  stat: path=/usr/lib/jvm
  register: usr_lib_jvm_exists
  tags: adoptopenjdk11

- name: Creating /usr/lib/jvm if not found
  file:
    path: /usr/lib/jvm
    state: directory
    owner: root
    group: root
    mode: 0755
  when: usr_lib_jvm_exists.stat.exists != True
  tags: adoptopenjdk11

- name: Check if jdk11 is already installed in the target location
  shell: ls -ld /usr/lib/jvm/jdk-11* >/dev/null 2>&1
  ignore_errors: yes
  register: adoptopenjdk11_installed
  tags:
    - adoptopenjdk11
    - skip_ansible_lint

- name: Install latest release if one not already installed (Linux/x64)
  unarchive:
    src: https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&type=jdk
    dest: /usr/lib/jvm
    remote_src: yes
  when:
    - adoptopenjdk11_installed.rc != 0
    - ansible_architecture == "x86_64"
  tags: adoptopenjdk11

- name: Install latest OpenJ9 release if one not already installed (Linux/s390x)
  unarchive:
    src: https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=openj9&os=linux&arch=s390x&release=latest&type=jdk
    dest: /usr/lib/jvm
    remote_src: yes
  when:
    - adoptopenjdk11_installed.rc != 0
    - ansible_architecture == "s390x"
  tags: adoptopenjdk11

- name: Install latest release if one not already installed (not Linux/x64 or Linux/armv7l)
  unarchive:
    src: https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=linux&arch={{ ansible_architecture }}&release=latest&type=jdk
    dest: /usr/lib/jvm
    remote_src: yes
  when:
    - adoptopenjdk11_installed.rc != 0
    - ansible_architecture != "x86_64"
    - ansible_architecture != "s390x"
    - ansible_architecture != "armv7l"
  tags: adoptopenjdk11

- name: Get /usr/lib/jvm/jdk11.* full path name
  shell: ls -ld /usr/lib/jvm/jdk-11.* 2>/dev/null | awk '{print $9}'
  register: adoptopenjdk11_dir
  when: adoptopenjdk11_installed.rc != 0
  tags: adoptopenjdk11

- name: Chown /usr/lib/jvm/jdk11.*
  file:
    path: '{{ adoptopenjdk11_dir.stdout }}'
    state: directory
    owner: root
    group: root
    recurse: yes
  when: adoptopenjdk11_installed.rc != 0
  tags: adoptopenjdk11
